services:
  app:
    build:
      context: .
      args:
        - UID=${UID:-}
        - GID=${GID:-}
    volumes:
      - "./:/code"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
